main = ".open-next/worker.js"
name = "awscloudclubtu"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "awscloudclubnepal.com "
custom_domain = true

[[routes]]
pattern = "www.awscloudclubnepal.com "
custom_domain = true
